### ISSUE TITLE
Cannot read property '__coverage__' of undefined

### ISSUE THREAD

**Issue by clubajax** [thedeeno/web-component-tester-istanbul#23]
Fresh install, I get this error:
Cannot read property '__coverage__' of undefined

The plugin is looking for "data.__coverage__"

steps.js line 90 does this:
runners[data.browserId].onEvent(data.event, data.data);

But there is no data.data emitted from socketIO.

**Comment by clubajax** [comment]
After installing with --save-dev, I got slightly different logged results. socket.io does emit a data property, but only on browser-start:

{ browserId: '0',
  event: 'browser-start',
  data: { url: 'http://localhost:2000/components/components/generated-index.html?cli_browser_id=0' } }

**Comment by clubajax** [comment]
It occurred to me I didn't provide the entire error:

chrome 48                Beginning tests via http://localhost:2000/components/components/generated-index.html?cli_browser_id=0
Missing error handler on `socket`.
TypeError: Cannot read property '__coverage__' of undefined
    at /Users/mwilcox/Sites/components/node_modules/web-component-tester-istanbul/lib/plugin.js:20:13
    at emitMany (events.js:108:13)
    at Context.emit (events.js:182:7)
    at BrowserRunner.onEvent (/Users/mwilcox/Sites/components/node_modules/web-component-tester/runner/browserrunner.js:136:18)
    at Socket.<anonymous> (/Users/mwilcox/Sites/components/node_modules/web-component-tester/runner/steps.js:90:31)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/Users/mwilcox/Sites/components/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/Users/mwilcox/Sites/components/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/Users/mwilcox/Sites/components/node_modules/socket.io/lib/client.js:193:14)

**Comment by visionscaper** [comment]
Hi @thedeeno, it seems that you have never published this fix as an npm module. The latest version is 0.10.0 instead of 0.10.1. Can you still publish it?
