### ISSUE TITLE
TypeError: glob pattern string required

### ISSUE THREAD

**Issue by eugef** [thedeeno/web-component-tester-istanbul#35]
When running with the latest web-component-tester 4.3.1 i have the following error:

```
TypeError: glob pattern string required
    at minimatch (/project/node_modules/web-component-tester-istanbul/node_modules/minimatch/minimatch.js:116:11)
    at Function.some (/project/node_modules/web-component-tester-istanbul/node_modules/lodash/dist/lodash.js:3956:25)
    at match (/project/node_modules/web-component-tester-istanbul/lib/middleware.js:94:14)
    at /project/node_modules/web-component-tester-istanbul/lib/middleware.js:71:54
    at Layer.handle [as handle_request] (/project/node_modules/web-component-tester/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/project/node_modules/web-component-tester/node_modules/express/lib/router/index.js:312:13)
    at /project/node_modules/web-component-tester/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/project/node_modules/web-component-tester/node_modules/express/lib/router/index.js:330:12)
    at next (/project/node_modules/web-component-tester/node_modules/express/lib/router/index.js:271:10)
    at /project/node_modules/web-component-tester/runner/webserver.js:96:17
```

Config is exactly the same as in readme.

**Comment by kevmarchant** [comment]
I'm having the same problem, is there a solution please?

**Comment by BHARATSEHRA** [comment]
Facing the same problem...Anyone please help
